### ISSUE TITLE
Unit-test not working - refactor and split

### ISSUE THREAD

**Issue by TomasKulhanek** [EUDAT-B2NOTE/b2note#364]
Unit-test are not working. This prevents from properly test potential upgrade to Python 3 and Django and other libraries/frameworks.
Executing `manage.py test` fails on `auth failed`

- [x] refactor 
- [x] split proper independent unit test from integration tests which needs properly configured external services like b2access etc. - consider to remove integration tests from automatic unit tests of CI

**Comment by TomasKulhanek** [comment]
- upgraded to python 3.6, django 2.2, migrated from mongoengine to djongo 
- sqlite version 3.8 and above is required
- mongodb version 4.x is required

**Comment by TomasKulhanek** [comment]
test authentication fails for testcases
```python
user = django.contrib.auth.authenticate(email=self.email,password=self.password)
```
fails internally on 
```
Unable to display children:Error resolving variables Traceback (most recent call last):
  File "/home/vagrant/py3/lib64/python3.6/site-packages/django/contrib/auth/__init__.py", line 68, in authenticate
    inspect.getcallargs(backend.authenticate, request, **credentials)
  File "/usr/lib64/python3.6/inspect.py", line 1344, in getcallargs
    (f_name, kw))
TypeError: authenticate() got multiple values for argument 'email'
```
cause is that the position argument is expected to be `email`, and set 'None' by default. Second 'email' named argument is provided with value. Workaround (fix):
```python
user = django.contrib.auth.authenticate(self.email,password=self.password) 
```

**Comment by TomasKulhanek** [comment]
Fixed by major refactor/upgrade and update
